[project]
name = "s-a-f-e-r"
version = "0.1.0"
description = "S.A.F.E.R Facial Recognition Module"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "numpy<2",
    "opencv-python",
    "pandas>=2.0",
    "pydantic",
    "pymysql",
    "ruff",
    "sqlalchemy",
    "fastapi",
    "uvicorn",
    "websockets",
    "dlib",
    "face-recognition",
    "face-recognition-models @ git+https://github.com/ageitgey/face_recognition_models"
]

[tool.uv.sources]
dlib = { path = "face_recognition/utils/dlib-19.22.99-cp310-cp310-win_amd64.whl" }