[project]
name = "s-a-f-e-r"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.20"
dependencies = [
    "numpy>=2.2.6",
    "opencv-python>=4.13.0.92",
    "pandas>=2.3.3",
    "pydantic>=2.13.4",
    "pymysql>=1.2.0",
    "ruff>=0.15.12",
    "sqlalchemy>=2.0.49",
]
